//
//  EmojiDataSource.m
//  ZhiWeibo
//
//  Created by junmin liu on 11-1-12.
//  Copyright 2011 Openlab. All rights reserved.
//

#import "EmojiDataSource.h"

static NSMutableDictionary *gEmojies;
static NSMutableArray *gRecentEmojies;

@implementation EmojiDataSource

+ (void)insertEmoji:(NSString *)_emoji phrase:(NSString *)_phrase forType:(NSString *)_type {
	NSMutableArray *emojiList = [gEmojies objectForKey:_type];
	if (emojiList == nil) {
		emojiList = [NSMutableArray array];
	}
	EmojiNode *node = [[EmojiNode alloc]initWithEmoji:_emoji phrase:_phrase];
	[emojiList addObject:node];
	[node release];
	[gEmojies setObject:emojiList forKey:_type];
}

+ (NSMutableDictionary *)emojies {
	if (gEmojies) {
		return gEmojies;
	}
	if (!gEmojies) {
		gEmojies = [[NSMutableDictionary alloc] init];
	}
	
	[EmojiDataSource insertEmojies];
	return gEmojies;
}

+ (NSMutableArray *)getEmojiNodes:(NSString *)_type {
	NSMutableDictionary *_emojies = [EmojiDataSource emojies];
	return [_emojies objectForKey:_type];
}

+ (NSMutableArray *)loadRecentEmojiNodes {
	if (gRecentEmojies) {
		return gRecentEmojies;
	}
	NSString *filePath = [WeiboEngine getCurrentUserStoreagePath:@"recentEmojiNodes.db"];
	NSMutableArray *_recentEmojies = [NSKeyedUnarchiver unarchiveObjectWithFile:filePath];
	gRecentEmojies = [_recentEmojies retain];
	//gRecentEmojies = [[NSMutableArray alloc] init];
	if (!gRecentEmojies) {
		gRecentEmojies = [[NSMutableArray alloc] init];
	}
	return gRecentEmojies;
}

+ (void)addRecentEmojiNodes:(EmojiNode *)node {
	if (!gRecentEmojies) {
		[EmojiDataSource loadRecentEmojiNodes];
	}
	int i = 0;
	int maxLength = 100;
	NSMutableArray *nodes = [NSMutableArray array];
	[nodes addObject:node];
	for (EmojiNode *en in gRecentEmojies) {
		i++;
		if ([en.phrase isEqualToString:node.phrase]) {
			continue;
		}
		[nodes addObject:en];
		if (i >= maxLength - 1) {
			break;
		}
	}
	[gRecentEmojies release];
	gRecentEmojies = [nodes retain];	
	
	NSString *filePath = [WeiboEngine getCurrentUserStoreagePath:@"recentEmojiNodes.db"];
	[NSKeyedArchiver archiveRootObject:gRecentEmojies toFile:filePath];
}

+ (void)insertEmojies {
	[EmojiDataSource insertEmoji:@"E415" phrase:[NSString stringWithFormat:@"%C", 0xe415] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E056" phrase:[NSString stringWithFormat:@"%C", 0xe056] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E057" phrase:[NSString stringWithFormat:@"%C", 0xe057] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E414" phrase:[NSString stringWithFormat:@"%C", 0xe414] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E405" phrase:[NSString stringWithFormat:@"%C", 0xe405] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E106" phrase:[NSString stringWithFormat:@"%C", 0xe106] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E418" phrase:[NSString stringWithFormat:@"%C", 0xe418] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E417" phrase:[NSString stringWithFormat:@"%C", 0xe417] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E40D" phrase:[NSString stringWithFormat:@"%C", 0xe40d] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E40A" phrase:[NSString stringWithFormat:@"%C", 0xe40a] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E404" phrase:[NSString stringWithFormat:@"%C", 0xe404] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E105" phrase:[NSString stringWithFormat:@"%C", 0xe105] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E409" phrase:[NSString stringWithFormat:@"%C", 0xe409] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E40E" phrase:[NSString stringWithFormat:@"%C", 0xe40e] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E402" phrase:[NSString stringWithFormat:@"%C", 0xe402] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E108" phrase:[NSString stringWithFormat:@"%C", 0xe108] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E403" phrase:[NSString stringWithFormat:@"%C", 0xe403] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E058" phrase:[NSString stringWithFormat:@"%C", 0xe058] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E407" phrase:[NSString stringWithFormat:@"%C", 0xe407] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E401" phrase:[NSString stringWithFormat:@"%C", 0xe401] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E40F" phrase:[NSString stringWithFormat:@"%C", 0xe40f] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E40B" phrase:[NSString stringWithFormat:@"%C", 0xe40b] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E406" phrase:[NSString stringWithFormat:@"%C", 0xe406] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E413" phrase:[NSString stringWithFormat:@"%C", 0xe413] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E411" phrase:[NSString stringWithFormat:@"%C", 0xe411] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E412" phrase:[NSString stringWithFormat:@"%C", 0xe412] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E410" phrase:[NSString stringWithFormat:@"%C", 0xe410] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E107" phrase:[NSString stringWithFormat:@"%C", 0xe107] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E059" phrase:[NSString stringWithFormat:@"%C", 0xe059] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E416" phrase:[NSString stringWithFormat:@"%C", 0xe416] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E408" phrase:[NSString stringWithFormat:@"%C", 0xe408] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E40C" phrase:[NSString stringWithFormat:@"%C", 0xe40c] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E11A" phrase:[NSString stringWithFormat:@"%C", 0xe11a] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E10C" phrase:[NSString stringWithFormat:@"%C", 0xe10c] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E32C" phrase:[NSString stringWithFormat:@"%C", 0xe32c] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E32A" phrase:[NSString stringWithFormat:@"%C", 0xe32a] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E32D" phrase:[NSString stringWithFormat:@"%C", 0xe32d] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E328" phrase:[NSString stringWithFormat:@"%C", 0xe328] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E32B" phrase:[NSString stringWithFormat:@"%C", 0xe32b] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E022" phrase:[NSString stringWithFormat:@"%C", 0xe022] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E023" phrase:[NSString stringWithFormat:@"%C", 0xe023] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E327" phrase:[NSString stringWithFormat:@"%C", 0xe327] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E329" phrase:[NSString stringWithFormat:@"%C", 0xe329] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E32E" phrase:[NSString stringWithFormat:@"%C", 0xe32e] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E32F" phrase:[NSString stringWithFormat:@"%C", 0xe32f] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E335" phrase:[NSString stringWithFormat:@"%C", 0xe335] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E334" phrase:[NSString stringWithFormat:@"%C", 0xe334] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E021" phrase:[NSString stringWithFormat:@"%C", 0xe021] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E337" phrase:[NSString stringWithFormat:@"%C", 0xe337] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E020" phrase:[NSString stringWithFormat:@"%C", 0xe020] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E336" phrase:[NSString stringWithFormat:@"%C", 0xe336] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E13C" phrase:[NSString stringWithFormat:@"%C", 0xe13c] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E330" phrase:[NSString stringWithFormat:@"%C", 0xe330] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E331" phrase:[NSString stringWithFormat:@"%C", 0xe331] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E326" phrase:[NSString stringWithFormat:@"%C", 0xe326] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E03E" phrase:[NSString stringWithFormat:@"%C", 0xe03e] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E11D" phrase:[NSString stringWithFormat:@"%C", 0xe11d] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E05A" phrase:[NSString stringWithFormat:@"%C", 0xe05a] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E00E" phrase:[NSString stringWithFormat:@"%C", 0xe00e] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E421" phrase:[NSString stringWithFormat:@"%C", 0xe421] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E420" phrase:[NSString stringWithFormat:@"%C", 0xe420] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E00D" phrase:[NSString stringWithFormat:@"%C", 0xe00d] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E010" phrase:[NSString stringWithFormat:@"%C", 0xe010] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E011" phrase:[NSString stringWithFormat:@"%C", 0xe011] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E41E" phrase:[NSString stringWithFormat:@"%C", 0xe41e] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E012" phrase:[NSString stringWithFormat:@"%C", 0xe012] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E422" phrase:[NSString stringWithFormat:@"%C", 0xe422] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E22E" phrase:[NSString stringWithFormat:@"%C", 0xe22e] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E22F" phrase:[NSString stringWithFormat:@"%C", 0xe22f] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E231" phrase:[NSString stringWithFormat:@"%C", 0xe231] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E230" phrase:[NSString stringWithFormat:@"%C", 0xe230] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E427" phrase:[NSString stringWithFormat:@"%C", 0xe427] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E41D" phrase:[NSString stringWithFormat:@"%C", 0xe41d] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E00F" phrase:[NSString stringWithFormat:@"%C", 0xe00f] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E41F" phrase:[NSString stringWithFormat:@"%C", 0xe41f] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E14C" phrase:[NSString stringWithFormat:@"%C", 0xe14c] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E201" phrase:[NSString stringWithFormat:@"%C", 0xe201] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E115" phrase:[NSString stringWithFormat:@"%C", 0xe115] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E428" phrase:[NSString stringWithFormat:@"%C", 0xe428] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E51F" phrase:[NSString stringWithFormat:@"%C", 0xe51f] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E429" phrase:[NSString stringWithFormat:@"%C", 0xe429] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E424" phrase:[NSString stringWithFormat:@"%C", 0xe424] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E423" phrase:[NSString stringWithFormat:@"%C", 0xe423] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E253" phrase:[NSString stringWithFormat:@"%C", 0xe253] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E426" phrase:[NSString stringWithFormat:@"%C", 0xe426] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E111" phrase:[NSString stringWithFormat:@"%C", 0xe111] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E425" phrase:[NSString stringWithFormat:@"%C", 0xe425] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E31E" phrase:[NSString stringWithFormat:@"%C", 0xe31e] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E31F" phrase:[NSString stringWithFormat:@"%C", 0xe31f] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E31D" phrase:[NSString stringWithFormat:@"%C", 0xe31d] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E001" phrase:[NSString stringWithFormat:@"%C", 0xe001] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E002" phrase:[NSString stringWithFormat:@"%C", 0xe002] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E005" phrase:[NSString stringWithFormat:@"%C", 0xe005] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E004" phrase:[NSString stringWithFormat:@"%C", 0xe004] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E51A" phrase:[NSString stringWithFormat:@"%C", 0xe51a] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E519" phrase:[NSString stringWithFormat:@"%C", 0xe519] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E518" phrase:[NSString stringWithFormat:@"%C", 0xe518] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E515" phrase:[NSString stringWithFormat:@"%C", 0xe515] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E516" phrase:[NSString stringWithFormat:@"%C", 0xe516] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E517" phrase:[NSString stringWithFormat:@"%C", 0xe517] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E51B" phrase:[NSString stringWithFormat:@"%C", 0xe51b] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E152" phrase:[NSString stringWithFormat:@"%C", 0xe152] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E04E" phrase:[NSString stringWithFormat:@"%C", 0xe04e] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E51C" phrase:[NSString stringWithFormat:@"%C", 0xe51c] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E51E" phrase:[NSString stringWithFormat:@"%C", 0xe51e] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E11C" phrase:[NSString stringWithFormat:@"%C", 0xe11c] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E536" phrase:[NSString stringWithFormat:@"%C", 0xe536] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E003" phrase:[NSString stringWithFormat:@"%C", 0xe003] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E41C" phrase:[NSString stringWithFormat:@"%C", 0xe41c] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E41B" phrase:[NSString stringWithFormat:@"%C", 0xe41b] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E419" phrase:[NSString stringWithFormat:@"%C", 0xe419] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E41A" phrase:[NSString stringWithFormat:@"%C", 0xe41a] forType:@"t1"]; 
	[EmojiDataSource insertEmoji:@"E04A" phrase:[NSString stringWithFormat:@"%C", 0xe04a] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E04B" phrase:[NSString stringWithFormat:@"%C", 0xe04b] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E049" phrase:[NSString stringWithFormat:@"%C", 0xe049] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E048" phrase:[NSString stringWithFormat:@"%C", 0xe048] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E04C" phrase:[NSString stringWithFormat:@"%C", 0xe04c] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E13D" phrase:[NSString stringWithFormat:@"%C", 0xe13d] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E443" phrase:[NSString stringWithFormat:@"%C", 0xe443] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E43E" phrase:[NSString stringWithFormat:@"%C", 0xe43e] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E04F" phrase:[NSString stringWithFormat:@"%C", 0xe04f] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E052" phrase:[NSString stringWithFormat:@"%C", 0xe052] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E053" phrase:[NSString stringWithFormat:@"%C", 0xe053] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E524" phrase:[NSString stringWithFormat:@"%C", 0xe524] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E52C" phrase:[NSString stringWithFormat:@"%C", 0xe52c] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E52A" phrase:[NSString stringWithFormat:@"%C", 0xe52a] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E531" phrase:[NSString stringWithFormat:@"%C", 0xe531] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E050" phrase:[NSString stringWithFormat:@"%C", 0xe050] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E527" phrase:[NSString stringWithFormat:@"%C", 0xe527] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E051" phrase:[NSString stringWithFormat:@"%C", 0xe051] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E10B" phrase:[NSString stringWithFormat:@"%C", 0xe10b] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E52B" phrase:[NSString stringWithFormat:@"%C", 0xe52b] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E52F" phrase:[NSString stringWithFormat:@"%C", 0xe52f] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E528" phrase:[NSString stringWithFormat:@"%C", 0xe528] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E01A" phrase:[NSString stringWithFormat:@"%C", 0xe01a] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E134" phrase:[NSString stringWithFormat:@"%C", 0xe134] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E530" phrase:[NSString stringWithFormat:@"%C", 0xe530] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E529" phrase:[NSString stringWithFormat:@"%C", 0xe529] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E526" phrase:[NSString stringWithFormat:@"%C", 0xe526] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E52D" phrase:[NSString stringWithFormat:@"%C", 0xe52d] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E521" phrase:[NSString stringWithFormat:@"%C", 0xe521] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E523" phrase:[NSString stringWithFormat:@"%C", 0xe523] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E52E" phrase:[NSString stringWithFormat:@"%C", 0xe52e] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E055" phrase:[NSString stringWithFormat:@"%C", 0xe055] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E525" phrase:[NSString stringWithFormat:@"%C", 0xe525] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E10A" phrase:[NSString stringWithFormat:@"%C", 0xe10a] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E109" phrase:[NSString stringWithFormat:@"%C", 0xe109] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E522" phrase:[NSString stringWithFormat:@"%C", 0xe522] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E019" phrase:[NSString stringWithFormat:@"%C", 0xe019] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E054" phrase:[NSString stringWithFormat:@"%C", 0xe054] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E520" phrase:[NSString stringWithFormat:@"%C", 0xe520] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E306" phrase:[NSString stringWithFormat:@"%C", 0xe306] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E030" phrase:[NSString stringWithFormat:@"%C", 0xe030] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E304" phrase:[NSString stringWithFormat:@"%C", 0xe304] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E110" phrase:[NSString stringWithFormat:@"%C", 0xe110] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E032" phrase:[NSString stringWithFormat:@"%C", 0xe032] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E305" phrase:[NSString stringWithFormat:@"%C", 0xe305] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E303" phrase:[NSString stringWithFormat:@"%C", 0xe303] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E118" phrase:[NSString stringWithFormat:@"%C", 0xe118] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E447" phrase:[NSString stringWithFormat:@"%C", 0xe447] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E119" phrase:[NSString stringWithFormat:@"%C", 0xe119] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E307" phrase:[NSString stringWithFormat:@"%C", 0xe307] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E308" phrase:[NSString stringWithFormat:@"%C", 0xe308] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E444" phrase:[NSString stringWithFormat:@"%C", 0xe444] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E441" phrase:[NSString stringWithFormat:@"%C", 0xe441] forType:@"t2"]; 
	[EmojiDataSource insertEmoji:@"E436" phrase:[NSString stringWithFormat:@"%C", 0xe436] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E437" phrase:[NSString stringWithFormat:@"%C", 0xe437] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E438" phrase:[NSString stringWithFormat:@"%C", 0xe438] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E43A" phrase:[NSString stringWithFormat:@"%C", 0xe43a] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E439" phrase:[NSString stringWithFormat:@"%C", 0xe439] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E43B" phrase:[NSString stringWithFormat:@"%C", 0xe43b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E117" phrase:[NSString stringWithFormat:@"%C", 0xe117] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E440" phrase:[NSString stringWithFormat:@"%C", 0xe440] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E442" phrase:[NSString stringWithFormat:@"%C", 0xe442] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E446" phrase:[NSString stringWithFormat:@"%C", 0xe446] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E445" phrase:[NSString stringWithFormat:@"%C", 0xe445] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E11B" phrase:[NSString stringWithFormat:@"%C", 0xe11b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E448" phrase:[NSString stringWithFormat:@"%C", 0xe448] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E033" phrase:[NSString stringWithFormat:@"%C", 0xe033] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E112" phrase:[NSString stringWithFormat:@"%C", 0xe112] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E325" phrase:[NSString stringWithFormat:@"%C", 0xe325] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E312" phrase:[NSString stringWithFormat:@"%C", 0xe312] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E310" phrase:[NSString stringWithFormat:@"%C", 0xe310] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E126" phrase:[NSString stringWithFormat:@"%C", 0xe126] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E127" phrase:[NSString stringWithFormat:@"%C", 0xe127] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E008" phrase:[NSString stringWithFormat:@"%C", 0xe008] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E03D" phrase:[NSString stringWithFormat:@"%C", 0xe03d] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E00C" phrase:[NSString stringWithFormat:@"%C", 0xe00c] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E12A" phrase:[NSString stringWithFormat:@"%C", 0xe12a] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E00A" phrase:[NSString stringWithFormat:@"%C", 0xe00a] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E00B" phrase:[NSString stringWithFormat:@"%C", 0xe00b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E009" phrase:[NSString stringWithFormat:@"%C", 0xe009] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E316" phrase:[NSString stringWithFormat:@"%C", 0xe316] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E129" phrase:[NSString stringWithFormat:@"%C", 0xe129] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E141" phrase:[NSString stringWithFormat:@"%C", 0xe141] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E142" phrase:[NSString stringWithFormat:@"%C", 0xe142] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E317" phrase:[NSString stringWithFormat:@"%C", 0xe317] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E128" phrase:[NSString stringWithFormat:@"%C", 0xe128] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E14B" phrase:[NSString stringWithFormat:@"%C", 0xe14b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E211" phrase:[NSString stringWithFormat:@"%C", 0xe211] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E114" phrase:[NSString stringWithFormat:@"%C", 0xe114] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E145" phrase:[NSString stringWithFormat:@"%C", 0xe145] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E144" phrase:[NSString stringWithFormat:@"%C", 0xe144] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E03F" phrase:[NSString stringWithFormat:@"%C", 0xe03f] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E313" phrase:[NSString stringWithFormat:@"%C", 0xe313] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E116" phrase:[NSString stringWithFormat:@"%C", 0xe116] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E10F" phrase:[NSString stringWithFormat:@"%C", 0xe10f] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E104" phrase:[NSString stringWithFormat:@"%C", 0xe104] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E103" phrase:[NSString stringWithFormat:@"%C", 0xe103] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E101" phrase:[NSString stringWithFormat:@"%C", 0xe101] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E102" phrase:[NSString stringWithFormat:@"%C", 0xe102] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E13F" phrase:[NSString stringWithFormat:@"%C", 0xe13f] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E140" phrase:[NSString stringWithFormat:@"%C", 0xe140] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E11F" phrase:[NSString stringWithFormat:@"%C", 0xe11f] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E12F" phrase:[NSString stringWithFormat:@"%C", 0xe12f] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E031" phrase:[NSString stringWithFormat:@"%C", 0xe031] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E30E" phrase:[NSString stringWithFormat:@"%C", 0xe30e] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E311" phrase:[NSString stringWithFormat:@"%C", 0xe311] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E113" phrase:[NSString stringWithFormat:@"%C", 0xe113] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E30F" phrase:[NSString stringWithFormat:@"%C", 0xe30f] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E13B" phrase:[NSString stringWithFormat:@"%C", 0xe13b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E42B" phrase:[NSString stringWithFormat:@"%C", 0xe42b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E42A" phrase:[NSString stringWithFormat:@"%C", 0xe42a] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E018" phrase:[NSString stringWithFormat:@"%C", 0xe018] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E016" phrase:[NSString stringWithFormat:@"%C", 0xe016] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E015" phrase:[NSString stringWithFormat:@"%C", 0xe015] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E014" phrase:[NSString stringWithFormat:@"%C", 0xe014] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E42C" phrase:[NSString stringWithFormat:@"%C", 0xe42c] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E42D" phrase:[NSString stringWithFormat:@"%C", 0xe42d] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E017" phrase:[NSString stringWithFormat:@"%C", 0xe017] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E013" phrase:[NSString stringWithFormat:@"%C", 0xe013] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E20E" phrase:[NSString stringWithFormat:@"%C", 0xe20e] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E20C" phrase:[NSString stringWithFormat:@"%C", 0xe20c] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E20F" phrase:[NSString stringWithFormat:@"%C", 0xe20f] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E20D" phrase:[NSString stringWithFormat:@"%C", 0xe20d] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E131" phrase:[NSString stringWithFormat:@"%C", 0xe131] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E12B" phrase:[NSString stringWithFormat:@"%C", 0xe12b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E130" phrase:[NSString stringWithFormat:@"%C", 0xe130] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E12D" phrase:[NSString stringWithFormat:@"%C", 0xe12d] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E324" phrase:[NSString stringWithFormat:@"%C", 0xe324] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E301" phrase:[NSString stringWithFormat:@"%C", 0xe301] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E148" phrase:[NSString stringWithFormat:@"%C", 0xe148] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E502" phrase:[NSString stringWithFormat:@"%C", 0xe502] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E03C" phrase:[NSString stringWithFormat:@"%C", 0xe03c] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E30A" phrase:[NSString stringWithFormat:@"%C", 0xe30a] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E042" phrase:[NSString stringWithFormat:@"%C", 0xe042] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E040" phrase:[NSString stringWithFormat:@"%C", 0xe040] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E041" phrase:[NSString stringWithFormat:@"%C", 0xe041] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E12C" phrase:[NSString stringWithFormat:@"%C", 0xe12c] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E007" phrase:[NSString stringWithFormat:@"%C", 0xe007] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E31A" phrase:[NSString stringWithFormat:@"%C", 0xe31a] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E13E" phrase:[NSString stringWithFormat:@"%C", 0xe13e] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E31B" phrase:[NSString stringWithFormat:@"%C", 0xe31b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E006" phrase:[NSString stringWithFormat:@"%C", 0xe006] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E302" phrase:[NSString stringWithFormat:@"%C", 0xe302] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E319" phrase:[NSString stringWithFormat:@"%C", 0xe319] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E321" phrase:[NSString stringWithFormat:@"%C", 0xe321] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E322" phrase:[NSString stringWithFormat:@"%C", 0xe322] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E314" phrase:[NSString stringWithFormat:@"%C", 0xe314] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E503" phrase:[NSString stringWithFormat:@"%C", 0xe503] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E10E" phrase:[NSString stringWithFormat:@"%C", 0xe10e] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E318" phrase:[NSString stringWithFormat:@"%C", 0xe318] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E43C" phrase:[NSString stringWithFormat:@"%C", 0xe43c] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E11E" phrase:[NSString stringWithFormat:@"%C", 0xe11e] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E323" phrase:[NSString stringWithFormat:@"%C", 0xe323] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E31C" phrase:[NSString stringWithFormat:@"%C", 0xe31c] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E034" phrase:[NSString stringWithFormat:@"%C", 0xe034] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E035" phrase:[NSString stringWithFormat:@"%C", 0xe035] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E045" phrase:[NSString stringWithFormat:@"%C", 0xe045] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E338" phrase:[NSString stringWithFormat:@"%C", 0xe338] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E047" phrase:[NSString stringWithFormat:@"%C", 0xe047] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E30C" phrase:[NSString stringWithFormat:@"%C", 0xe30c] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E044" phrase:[NSString stringWithFormat:@"%C", 0xe044] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E30B" phrase:[NSString stringWithFormat:@"%C", 0xe30b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E043" phrase:[NSString stringWithFormat:@"%C", 0xe043] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E120" phrase:[NSString stringWithFormat:@"%C", 0xe120] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E33B" phrase:[NSString stringWithFormat:@"%C", 0xe33b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E33F" phrase:[NSString stringWithFormat:@"%C", 0xe33f] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E341" phrase:[NSString stringWithFormat:@"%C", 0xe341] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E34C" phrase:[NSString stringWithFormat:@"%C", 0xe34c] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E344" phrase:[NSString stringWithFormat:@"%C", 0xe344] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E342" phrase:[NSString stringWithFormat:@"%C", 0xe342] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E33D" phrase:[NSString stringWithFormat:@"%C", 0xe33d] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E33E" phrase:[NSString stringWithFormat:@"%C", 0xe33e] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E340" phrase:[NSString stringWithFormat:@"%C", 0xe340] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E34D" phrase:[NSString stringWithFormat:@"%C", 0xe34d] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E339" phrase:[NSString stringWithFormat:@"%C", 0xe339] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E147" phrase:[NSString stringWithFormat:@"%C", 0xe147] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E343" phrase:[NSString stringWithFormat:@"%C", 0xe343] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E33C" phrase:[NSString stringWithFormat:@"%C", 0xe33c] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E33A" phrase:[NSString stringWithFormat:@"%C", 0xe33a] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E43F" phrase:[NSString stringWithFormat:@"%C", 0xe43f] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E34B" phrase:[NSString stringWithFormat:@"%C", 0xe34b] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E046" phrase:[NSString stringWithFormat:@"%C", 0xe046] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E345" phrase:[NSString stringWithFormat:@"%C", 0xe345] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E346" phrase:[NSString stringWithFormat:@"%C", 0xe346] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E348" phrase:[NSString stringWithFormat:@"%C", 0xe348] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E347" phrase:[NSString stringWithFormat:@"%C", 0xe347] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E34A" phrase:[NSString stringWithFormat:@"%C", 0xe34a] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E349" phrase:[NSString stringWithFormat:@"%C", 0xe349] forType:@"t3"]; 
	[EmojiDataSource insertEmoji:@"E036" phrase:[NSString stringWithFormat:@"%C", 0xe036] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E157" phrase:[NSString stringWithFormat:@"%C", 0xe157] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E038" phrase:[NSString stringWithFormat:@"%C", 0xe038] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E153" phrase:[NSString stringWithFormat:@"%C", 0xe153] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E155" phrase:[NSString stringWithFormat:@"%C", 0xe155] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E14D" phrase:[NSString stringWithFormat:@"%C", 0xe14d] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E156" phrase:[NSString stringWithFormat:@"%C", 0xe156] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E501" phrase:[NSString stringWithFormat:@"%C", 0xe501] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E158" phrase:[NSString stringWithFormat:@"%C", 0xe158] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E43D" phrase:[NSString stringWithFormat:@"%C", 0xe43d] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E037" phrase:[NSString stringWithFormat:@"%C", 0xe037] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E504" phrase:[NSString stringWithFormat:@"%C", 0xe504] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E44A" phrase:[NSString stringWithFormat:@"%C", 0xe44a] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E146" phrase:[NSString stringWithFormat:@"%C", 0xe146] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E50A" phrase:[NSString stringWithFormat:@"%C", 0xe50a] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E505" phrase:[NSString stringWithFormat:@"%C", 0xe505] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E506" phrase:[NSString stringWithFormat:@"%C", 0xe506] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E122" phrase:[NSString stringWithFormat:@"%C", 0xe122] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E508" phrase:[NSString stringWithFormat:@"%C", 0xe508] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E509" phrase:[NSString stringWithFormat:@"%C", 0xe509] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E03B" phrase:[NSString stringWithFormat:@"%C", 0xe03b] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E04D" phrase:[NSString stringWithFormat:@"%C", 0xe04d] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E449" phrase:[NSString stringWithFormat:@"%C", 0xe449] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E44B" phrase:[NSString stringWithFormat:@"%C", 0xe44b] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E51D" phrase:[NSString stringWithFormat:@"%C", 0xe51d] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E44C" phrase:[NSString stringWithFormat:@"%C", 0xe44c] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E124" phrase:[NSString stringWithFormat:@"%C", 0xe124] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E121" phrase:[NSString stringWithFormat:@"%C", 0xe121] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E433" phrase:[NSString stringWithFormat:@"%C", 0xe433] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E202" phrase:[NSString stringWithFormat:@"%C", 0xe202] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E135" phrase:[NSString stringWithFormat:@"%C", 0xe135] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E01C" phrase:[NSString stringWithFormat:@"%C", 0xe01c] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E01D" phrase:[NSString stringWithFormat:@"%C", 0xe01d] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E10D" phrase:[NSString stringWithFormat:@"%C", 0xe10d] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E136" phrase:[NSString stringWithFormat:@"%C", 0xe136] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E42E" phrase:[NSString stringWithFormat:@"%C", 0xe42e] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E01B" phrase:[NSString stringWithFormat:@"%C", 0xe01b] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E15A" phrase:[NSString stringWithFormat:@"%C", 0xe15a] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E159" phrase:[NSString stringWithFormat:@"%C", 0xe159] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E432" phrase:[NSString stringWithFormat:@"%C", 0xe432] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E430" phrase:[NSString stringWithFormat:@"%C", 0xe430] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E431" phrase:[NSString stringWithFormat:@"%C", 0xe431] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E42F" phrase:[NSString stringWithFormat:@"%C", 0xe42f] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E01E" phrase:[NSString stringWithFormat:@"%C", 0xe01e] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E039" phrase:[NSString stringWithFormat:@"%C", 0xe039] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E435" phrase:[NSString stringWithFormat:@"%C", 0xe435] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E01F" phrase:[NSString stringWithFormat:@"%C", 0xe01f] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E125" phrase:[NSString stringWithFormat:@"%C", 0xe125] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E03A" phrase:[NSString stringWithFormat:@"%C", 0xe03a] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E14E" phrase:[NSString stringWithFormat:@"%C", 0xe14e] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E252" phrase:[NSString stringWithFormat:@"%C", 0xe252] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E137" phrase:[NSString stringWithFormat:@"%C", 0xe137] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E209" phrase:[NSString stringWithFormat:@"%C", 0xe209] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E154" phrase:[NSString stringWithFormat:@"%C", 0xe154] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E133" phrase:[NSString stringWithFormat:@"%C", 0xe133] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E150" phrase:[NSString stringWithFormat:@"%C", 0xe150] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E320" phrase:[NSString stringWithFormat:@"%C", 0xe320] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E123" phrase:[NSString stringWithFormat:@"%C", 0xe123] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E132" phrase:[NSString stringWithFormat:@"%C", 0xe132] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E143" phrase:[NSString stringWithFormat:@"%C", 0xe143] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E50B" phrase:[NSString stringWithFormat:@"%C", 0xe50b] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E514" phrase:[NSString stringWithFormat:@"%C", 0xe514] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E513" phrase:[NSString stringWithFormat:@"%C", 0xe513] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E50C" phrase:[NSString stringWithFormat:@"%C", 0xe50c] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E50D" phrase:[NSString stringWithFormat:@"%C", 0xe50d] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E511" phrase:[NSString stringWithFormat:@"%C", 0xe511] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E50F" phrase:[NSString stringWithFormat:@"%C", 0xe50f] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E512" phrase:[NSString stringWithFormat:@"%C", 0xe512] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E510" phrase:[NSString stringWithFormat:@"%C", 0xe510] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E50E" phrase:[NSString stringWithFormat:@"%C", 0xe50e] forType:@"t4"]; 
	[EmojiDataSource insertEmoji:@"E21C" phrase:[NSString stringWithFormat:@"%C", 0xe21c] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E21D" phrase:[NSString stringWithFormat:@"%C", 0xe21d] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E21E" phrase:[NSString stringWithFormat:@"%C", 0xe21e] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E21F" phrase:[NSString stringWithFormat:@"%C", 0xe21f] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E220" phrase:[NSString stringWithFormat:@"%C", 0xe220] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E221" phrase:[NSString stringWithFormat:@"%C", 0xe221] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E222" phrase:[NSString stringWithFormat:@"%C", 0xe222] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E223" phrase:[NSString stringWithFormat:@"%C", 0xe223] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E224" phrase:[NSString stringWithFormat:@"%C", 0xe224] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E225" phrase:[NSString stringWithFormat:@"%C", 0xe225] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E210" phrase:[NSString stringWithFormat:@"%C", 0xe210] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E232" phrase:[NSString stringWithFormat:@"%C", 0xe232] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E233" phrase:[NSString stringWithFormat:@"%C", 0xe233] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E235" phrase:[NSString stringWithFormat:@"%C", 0xe235] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E234" phrase:[NSString stringWithFormat:@"%C", 0xe234] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E236" phrase:[NSString stringWithFormat:@"%C", 0xe236] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E237" phrase:[NSString stringWithFormat:@"%C", 0xe237] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E238" phrase:[NSString stringWithFormat:@"%C", 0xe238] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E239" phrase:[NSString stringWithFormat:@"%C", 0xe239] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E23B" phrase:[NSString stringWithFormat:@"%C", 0xe23b] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E23A" phrase:[NSString stringWithFormat:@"%C", 0xe23a] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E23D" phrase:[NSString stringWithFormat:@"%C", 0xe23d] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E23C" phrase:[NSString stringWithFormat:@"%C", 0xe23c] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E24D" phrase:[NSString stringWithFormat:@"%C", 0xe24d] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E212" phrase:[NSString stringWithFormat:@"%C", 0xe212] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E24C" phrase:[NSString stringWithFormat:@"%C", 0xe24c] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E213" phrase:[NSString stringWithFormat:@"%C", 0xe213] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E214" phrase:[NSString stringWithFormat:@"%C", 0xe214] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E507" phrase:[NSString stringWithFormat:@"%C", 0xe507] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E203" phrase:[NSString stringWithFormat:@"%C", 0xe203] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E20B" phrase:[NSString stringWithFormat:@"%C", 0xe20b] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E22A" phrase:[NSString stringWithFormat:@"%C", 0xe22a] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E22B" phrase:[NSString stringWithFormat:@"%C", 0xe22b] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E226" phrase:[NSString stringWithFormat:@"%C", 0xe226] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E227" phrase:[NSString stringWithFormat:@"%C", 0xe227] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E22C" phrase:[NSString stringWithFormat:@"%C", 0xe22c] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E22D" phrase:[NSString stringWithFormat:@"%C", 0xe22d] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E215" phrase:[NSString stringWithFormat:@"%C", 0xe215] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E216" phrase:[NSString stringWithFormat:@"%C", 0xe216] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E217" phrase:[NSString stringWithFormat:@"%C", 0xe217] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E218" phrase:[NSString stringWithFormat:@"%C", 0xe218] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E228" phrase:[NSString stringWithFormat:@"%C", 0xe228] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E151" phrase:[NSString stringWithFormat:@"%C", 0xe151] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E138" phrase:[NSString stringWithFormat:@"%C", 0xe138] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E139" phrase:[NSString stringWithFormat:@"%C", 0xe139] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E13A" phrase:[NSString stringWithFormat:@"%C", 0xe13a] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E208" phrase:[NSString stringWithFormat:@"%C", 0xe208] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E14F" phrase:[NSString stringWithFormat:@"%C", 0xe14f] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E20A" phrase:[NSString stringWithFormat:@"%C", 0xe20a] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E434" phrase:[NSString stringWithFormat:@"%C", 0xe434] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E309" phrase:[NSString stringWithFormat:@"%C", 0xe309] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E315" phrase:[NSString stringWithFormat:@"%C", 0xe315] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E30D" phrase:[NSString stringWithFormat:@"%C", 0xe30d] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E207" phrase:[NSString stringWithFormat:@"%C", 0xe207] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E229" phrase:[NSString stringWithFormat:@"%C", 0xe229] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E206" phrase:[NSString stringWithFormat:@"%C", 0xe206] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E205" phrase:[NSString stringWithFormat:@"%C", 0xe205] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E204" phrase:[NSString stringWithFormat:@"%C", 0xe204] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E12E" phrase:[NSString stringWithFormat:@"%C", 0xe12e] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E250" phrase:[NSString stringWithFormat:@"%C", 0xe250] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E251" phrase:[NSString stringWithFormat:@"%C", 0xe251] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E14A" phrase:[NSString stringWithFormat:@"%C", 0xe14a] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E149" phrase:[NSString stringWithFormat:@"%C", 0xe149] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E23F" phrase:[NSString stringWithFormat:@"%C", 0xe23f] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E240" phrase:[NSString stringWithFormat:@"%C", 0xe240] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E241" phrase:[NSString stringWithFormat:@"%C", 0xe241] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E242" phrase:[NSString stringWithFormat:@"%C", 0xe242] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E243" phrase:[NSString stringWithFormat:@"%C", 0xe243] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E244" phrase:[NSString stringWithFormat:@"%C", 0xe244] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E245" phrase:[NSString stringWithFormat:@"%C", 0xe245] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E246" phrase:[NSString stringWithFormat:@"%C", 0xe246] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E247" phrase:[NSString stringWithFormat:@"%C", 0xe247] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E248" phrase:[NSString stringWithFormat:@"%C", 0xe248] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E249" phrase:[NSString stringWithFormat:@"%C", 0xe249] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E24A" phrase:[NSString stringWithFormat:@"%C", 0xe24a] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E24B" phrase:[NSString stringWithFormat:@"%C", 0xe24b] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E23E" phrase:[NSString stringWithFormat:@"%C", 0xe23e] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E532" phrase:[NSString stringWithFormat:@"%C", 0xe532] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E533" phrase:[NSString stringWithFormat:@"%C", 0xe533] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E534" phrase:[NSString stringWithFormat:@"%C", 0xe534] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E535" phrase:[NSString stringWithFormat:@"%C", 0xe535] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E21A" phrase:[NSString stringWithFormat:@"%C", 0xe21a] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E219" phrase:[NSString stringWithFormat:@"%C", 0xe219] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E21B" phrase:[NSString stringWithFormat:@"%C", 0xe21b] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E02F" phrase:[NSString stringWithFormat:@"%C", 0xe02f] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E024" phrase:[NSString stringWithFormat:@"%C", 0xe024] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E025" phrase:[NSString stringWithFormat:@"%C", 0xe025] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E026" phrase:[NSString stringWithFormat:@"%C", 0xe026] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E027" phrase:[NSString stringWithFormat:@"%C", 0xe027] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E028" phrase:[NSString stringWithFormat:@"%C", 0xe028] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E029" phrase:[NSString stringWithFormat:@"%C", 0xe029] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E02A" phrase:[NSString stringWithFormat:@"%C", 0xe02a] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E02B" phrase:[NSString stringWithFormat:@"%C", 0xe02b] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E02C" phrase:[NSString stringWithFormat:@"%C", 0xe02c] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E02D" phrase:[NSString stringWithFormat:@"%C", 0xe02d] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E02E" phrase:[NSString stringWithFormat:@"%C", 0xe02e] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E332" phrase:[NSString stringWithFormat:@"%C", 0xe332] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E333" phrase:[NSString stringWithFormat:@"%C", 0xe333] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E24E" phrase:[NSString stringWithFormat:@"%C", 0xe24e] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E24F" phrase:[NSString stringWithFormat:@"%C", 0xe24f] forType:@"t5"]; 
	[EmojiDataSource insertEmoji:@"E537" phrase:[NSString stringWithFormat:@"%C", 0xe537] forType:@"t5"];  
}

@end
